# Generated by Django 5.1.5 on 2025-01-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_years_experience', models.PositiveIntegerField(default=0)),
                ('min_projects', models.PositiveIntegerField(default=0)),
                ('certifications_required', models.TextField(blank=True, null=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.jobrole')),
            ],
        ),
    ]
