# Generated by Django 5.1.5 on 2025-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='job_role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='certifications_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='min_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluationcriteria',
            name='min_years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
    ]
