# Generated by Django 5.1.5 on 2025-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_evaluationcriteria_job_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("specific_area", models.CharField(max_length=255)),
                ("keywords", models.TextField(help_text="Comma-separated keywords")),
                ("score", models.FloatField(default=0.0)),
            ],
        ),
    ]
