# Generated by Django 5.1.5 on 2025-01-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_questioncriteria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questioncriteria",
            name="score",
        ),
    ]
