# Generated by Django 5.1.5 on 2025-01-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_questioncriteria_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
