# Generated by Django 5.1.5 on 2025-01-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_question_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
