# Generated by Django 5.1.5 on 2025-02-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_question_question_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
