# Generated by Django 5.1.5 on 2025-01-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("password", models.CharField(max_length=255, verbose_name="Password")),
                (
                    "resume_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Score for the resume (0-100)",
                        null=True,
                        verbose_name="Resume Score",
                    ),
                ),
                ("resume_link", models.URLField(verbose_name="Resume Link")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
        ),
    ]
