# Generated by Django 5.1.5 on 2025-02-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplyPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('resume_link', models.URLField(verbose_name='Resume Link')),
                ('resume_score', models.IntegerField(blank=True, help_text='Score for the resume (0-100)', null=True, verbose_name='Resume Score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
