# Generated by Django 5.1.5 on 2025-02-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ApplyPage', '0002_candidate_delete_resume'),
        ('dashboard', '0010_delete_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=255)),
                ('total_score', models.IntegerField(default=0, verbose_name='Total Interview Score')),
                ('video_call_path', models.URLField(blank=True, null=True, verbose_name='Video Call Recording Path')),
                ('interview_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='ApplyPage.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_text', models.TextField()),
                ('score', models.IntegerField()),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Interview.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.question')),
            ],
        ),
    ]
