# Generated by Django 5.1.5 on 2025-02-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
        ('dashboard', '0010_delete_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.evaluationcriteria'),
        ),
    ]
