# Generated by Django 5.1.5 on 2025-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_alter_interview_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='job_role',
            field=models.CharField(max_length=255),
        ),
    ]
