# Generated by Django 5.1.5 on 2025-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0004_remove_interview_video_call_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='video_path',
            field=models.FileField(null=True, upload_to='interview_recordings/'),
        ),
    ]
